// <auto-generated />
using GeoMottuApi.Infrastructure.Data.AppData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace GeoMottuApi.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20250430235336_AddLimitSizeForCamps")]
    partial class AddLimitSizeForCamps
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GeoMottuApi.Domain.Entities.MotoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("MOTO_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Chassi")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("NVARCHAR2(17)")
                        .HasColumnName("CHASSI_MOTO");

                    b.Property<string>("CodPlacaIot")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("CD_IOT_PLACA");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MOTO_MODELO");

                    b.Property<int>("Motor")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("MOTOR_MOTO");

                    b.Property<string>("Placa")
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("PLACA_MOTO");

                    b.HasKey("Id");

                    b.HasIndex("Placa", "CodPlacaIot", "Chassi")
                        .IsUnique()
                        .HasFilter("\"PLACA_MOTO\" IS NOT NULL AND \"CD_IOT_PLACA\" IS NOT NULL");

                    b.ToTable("TB_GEOMOTTU_MOTO");
                });
#pragma warning restore 612, 618
        }
    }
}
